name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+"

permissions:
  contents: write

jobs:
  publish:
    if: github.repository == 'rameel/vue-hotkey'
    name: "Publish Packages"
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Build packages
        run: npm run build

      - name: Publish packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Archive packages (.zip)
        run: zip -r ramstack.vue-hotkey-${{ github.ref_name }}.zip ./dist/*

      - name: Archive packages (.tar.gz)
        run: tar -czvf ramstack.vue-hotkey-${{ github.ref_name }}.tar.gz ./dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            ramstack.vue-hotkey-${{ github.ref_name }}.zip
            ramstack.vue-hotkey-${{ github.ref_name }}.tar.gz
